name = "google-analytics-views-cloudflare-worker"
account_id = "080a63e1b12d608cd1bbed2f525682a9"
main = "worker.ts"
compatibility_date = "2024-11-15"
workers_dev = true
SERVICE_ACCOUNT_CREDENTIALS = ""
GA_PROPERTY_ID = ""
keep-vars = true
route = { pattern = "*toknow.ai/pageviews*", zone_name = "toknow.ai" }

[observability]
enabled = true
